S3 Inventory Athena doc sample query fix
The sample Athena query for ORC-formatted inventory uses `bigint` instead of
`timestamp` for the data type. This results in an error when attempting to
query the table:

> HIVE_CURSOR_ERROR: Failed to read ORC file: ...